esphome:
  name: my_ls

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - light.toggle: light_1

  - platform: status
    name: "My LS Status"

output:
  - platform: gpio
    pin: GPIO14
    id: relay_1

light:
  - platform: binary
    name: "My Light"
    id: light_1
    output: relay_1

status_led:
  pin:
    number: GPIO5
    inverted: yes
